version: '3'

services:
  spring-app:
    build:
      context: . 
    ports:
      - "8093:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: A35675465

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: A35675465
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

